name: build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:


env:
  IMAGE_NAME_FULL: ghcr.io/twelvelabs/dv-api-full
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # pin@v3.5.3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # pin@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # pin@v2.5.0

      - name: Build
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # pin@v4.0.0
        with:
          load: true
          build-args: |
            APP_TARGET=full
          context: .
          cache-from: |
            type=gha
            type=registry,ref=${{ env.IMAGE_NAME_FULL }}:latest
            type=registry,ref=${{ env.IMAGE_NAME_FULL }}:buildcache
          cache-to: |
            type=gha
          tags: ${{ env.IMAGE_NAME_FULL }}:latest
          target: full

      - name: Lint
        run: make lint

      - name: Test
        run: make test
